CREATE TABLE ACCOUNTS (
	ACNT_ID BIGINT IDENTITY NOT NULL,
	ACNT_CREATED_TIME TIMESTAMP NOT NULL,
	ACNT_UPDATED_TIME TIMESTAMP,
	ACNT_REMARK VARCHAR(65535),
	ACNT_ACTIVE INTEGER NOT NULL,
	ACNT_MCHT_ID BIGINT NOT NULL,
	ACNT_ACTP_ID BIGINT NOT NULL,
	ACNT_ACST_ID BIGINT NOT NULL,
	PRIMARY KEY (ACNT_ID,ACNT_MCHT_ID,ACNT_ACTP_ID,ACNT_ACST_ID)
);
CREATE TABLE ACCOUNT_STATUSES (
	ACST_ID BIGINT IDENTITY NOT NULL,
	ACST_NAME VARCHAR(32) NOT NULL,
	ACST_DESCRIPTION VARCHAR(65535),
	ACST_ACTIVE INTEGER NOT NULL,
	ACST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (ACST_ID)
);
CREATE TABLE ACCOUNT_TYPES (
	ACTP_ID BIGINT IDENTITY NOT NULL,
	ACTP_NAME VARCHAR(32) NOT NULL,
	ACTP_DESCRIPTION VARCHAR(65535),
	ACTP_ACTIVE INTEGER NOT NULL,
	ACTP_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (ACTP_ID)
);
CREATE TABLE ADMINISTRATORS (
	ADMN_ID BIGINT IDENTITY NOT NULL,
	ADMN_USERNAME VARCHAR(32) NOT NULL,
	ADMN_PASSWORD VARCHAR(32) NOT NULL,
	ADMN_FIRST_NAME VARCHAR(32) NOT NULL,
	ADMN_LAST_NAME VARCHAR(32) NOT NULL,
	ADMN_EMAIL VARCHAR(32) NOT NULL,
	ADMN_PROFILE_IMAGE LONGVARBINARY,
	ADMN_REMARK VARCHAR(65535),
	ADMN_CREATED_TIME TIMESTAMP NOT NULL,
	ADMN_UPDATED_TIME TIMESTAMP,
	ADMN_ACTIVE INTEGER NOT NULL,
	ADMN_ROLE_ID BIGINT NOT NULL,
	PRIMARY KEY (ADMN_ID,ADMN_ROLE_ID)
);
CREATE TABLE CREDENTIALS (
	CRDT_ID BIGINT IDENTITY NOT NULL,
	CRDT_CONTENT VARCHAR(32) NOT NULL,
	CRDT_EXPIRATION_TIME TIMESTAMP NOT NULL,
	CRDT_REMARK VARCHAR(65535),
	CRDT_CREATED_TIME TIMESTAMP NOT NULL,
	CRDT_UPDATED_TIME TIMESTAMP,
	CRDT_ACTIVE INTEGER NOT NULL,
	CRDT_CRST_ID BIGINT NOT NULL,
	CRDT_CRTP_ID BIGINT NOT NULL,
	CRDT_CRETED_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (CRDT_ID,CRDT_CRST_ID,CRDT_CRTP_ID)
);
CREATE TABLE CREDENTIAL_STATUSES (
	CRST_ID BIGINT IDENTITY NOT NULL,
	CRST_NAME VARCHAR(32) NOT NULL,
	CRST_DESCRIPTION VARCHAR(65535),
	CRST_ACTIVE INTEGER NOT NULL,
	CRST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (CRST_ID)
);
CREATE TABLE CREDENTIAL_TYPES (
	CRTP_ID BIGINT IDENTITY NOT NULL,
	CRTP_NAME VARCHAR(32) NOT NULL,
	CRTP_DESCRIPTION VARCHAR(65535),
	CRTP_ACTIVE INTEGER NOT NULL,
	CRTP_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (CRTP_ID)
);
CREATE TABLE CURRENCIES (
	CRCY_ID BIGINT IDENTITY NOT NULL,
	CRCY_NAME VARCHAR(32) NOT NULL,
	CRCY_DESCRIPTION VARCHAR(65535),
	CRCY_ACTIVE INTEGER NOT NULL,
	CRCY_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (CRCY_ID)
);
CREATE TABLE CUSTOMERS (
	CSTM_ID BIGINT IDENTITY NOT NULL,
	CSTM_FIRST_NAME VARCHAR(32) NOT NULL,
	CSTM_LAST_NAME VARCHAR(32) NOT NULL,
	CSTM_EMAIL VARCHAR(32) NOT NULL,
	CSTM_ADDRESS_1 VARCHAR(128) NOT NULL,
	CSTM_ADDRESS_2 VARCHAR(128),
	CSTM_CITY VARCHAR(32) NOT NULL,
	CSTM_STATE VARCHAR(32) NOT NULL,
	CSTM_ZIP_CODE VARCHAR(32) NOT NULL,
	CSTM_COUNTRY VARCHAR(32) NOT NULL,
	CSTM_TEL VARCHAR(32),
	CSTM_CREATED_TIME TIMESTAMP NOT NULL,
	CSTM_UPDATED_TIME TIMESTAMP,
	CSTM_REMARK VARCHAR(65535),
	CSTM_ACTIVE INTEGER NOT NULL,
	CSTM_CSST_ID BIGINT NOT NULL,
	CSTM_CSLG_ID BIGINT,
	PRIMARY KEY (CSTM_ID,CSTM_CSST_ID)
);
CREATE TABLE CUSTOMER_LOGINS (
	CSLG_ID BIGINT IDENTITY NOT NULL,
	CSLG_LOGIN_EMAIL VARCHAR(32) NOT NULL,
	CSLG_LOGIN_PASSWORD VARCHAR(32) NOT NULL,
	CSLG_FIRST_NAME VARCHAR(32) NOT NULL,
	CSLG_LAST_NAME VARCHAR(32) NOT NULL,
	CSLG_CREATED_TIME TIMESTAMP NOT NULL,
	CSLG_UPDATED_TIME TIMESTAMP NOT NULL,
	CSLG_REMARK VARCHAR(65535),
	CSLG_PROFILE_IMAGE LONGVARBINARY,
	CSLG__ACTIVE INTEGER NOT NULL,
	CSLG_CSLS_ID BIGINT NOT NULL,
	CSLG_ACTIVE VARCHAR NOT NULL,
	FIRST_NAME VARCHAR(32) NOT NULL,
	LAST_NAME VARCHAR(32) NOT NULL,
	PRIMARY KEY (CSLG_ID,CSLG_CSLS_ID)
);
CREATE TABLE CUSTOMER_LOGIN_STATUSES (
	CSLS_ID BIGINT IDENTITY NOT NULL,
	CSLS_NAME VARCHAR(32) NOT NULL,
	CSLS_DESCRIPTION VARCHAR(65535),
	CSLS_ACTIVE INTEGER NOT NULL,
	CSLS_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (CSLS_ID)
);
CREATE TABLE CUSTOMER_STATUSES (
	CSST_ID BIGINT IDENTITY NOT NULL,
	CSST_NAME VARCHAR(32) NOT NULL,
	CSST_DESCRIPTION VARCHAR(65535),
	CSST_ACTIVE INTEGER NOT NULL,
	CSST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (CSST_ID)
);
CREATE TABLE ENCRYPTIONS (
	ENCR_ID BIGINT IDENTITY NOT NULL,
	ENCR_KEY VARCHAR(128) NOT NULL,
	ENCR_CREATED_TIME TIMESTAMP NOT NULL,
	ENCR_UPDATED_TIME TIMESTAMP,
	ENCR_REMARK VARCHAR(65535),
	ENCR_ACTIVE INTEGER NOT NULL,
	ENCR_ENTP_ID BIGINT NOT NULL,
	PRIMARY KEY (ENCR_ID,ENCR_ENTP_ID)
);
CREATE TABLE ENCRYPTION_TYPES (
	ENTP_ID BIGINT IDENTITY NOT NULL,
	ENTP_NAME VARCHAR(32) NOT NULL,
	ENTP_DESCRIPTION VARCHAR(65535),
	ENTP_ACTIVE INTEGER NOT NULL,
	ENTP_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (ENTP_ID)
);
CREATE TABLE FEES (
	FEE_ID BIGINT IDENTITY NOT NULL,
	FEE_VALUE FLOAT NOT NULL,
	FEE_REMARK VARCHAR(65535),
	FEE_CREATED_TIME TIMESTAMP NOT NULL,
	FEE_UPDATED_TIME TIMESTAMP,
	FEE_ACTIVE INTEGER NOT NULL,
	FEE_FETP_ID BIGINT NOT NULL,
	PRIMARY KEY (FEE_ID,FEE_FETP_ID)
);
CREATE TABLE FEE_TYPES (
	FETP_ID BIGINT IDENTITY NOT NULL,
	FETP_NAME VARCHAR(32) NOT NULL,
	FETP_DESCRIPTION VARCHAR(65535),
	FETP_ACTIVE INTEGER NOT NULL,
	FETP_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (FETP_ID)
);
CREATE TABLE MERCHANTS (
	MCHT_ID BIGINT IDENTITY NOT NULL,
	MCHT_NAME VARCHAR(32) NOT NULL,
	MCHT_ADDRESS VARCHAR(128),
	MCHT_CONTACT VARCHAR(32),
	MCHT_TEL VARCHAR(32),
	MCHT_EMAIL VARCHAR(32),
	MCHT_LOGO_IMAGE LONGVARBINARY,
	MCHT_CREATED_TIME TIMESTAMP NOT NULL,
	MCHT_UPDATED_TIME TIMESTAMP,
	MCHT_REMARK VARCHAR(65535),
	MCHT_ACTIVE INTEGER NOT NULL,
	MCHT_MCST_ID BIGINT NOT NULL,
	MCHT_CRDT_ID BIGINT NOT NULL,
	MCHT_ENCR_ID BIGINT NOT NULL,
	MCHT_FEE_COMMISSION_ID BIGINT NOT NULL,
	MCHT_FEE_RETURN_ID BIGINT NOT NULL,
	PRIMARY KEY (MCHT_ID,MCHT_MCST_ID,MCHT_CRDT_ID,MCHT_ENCR_ID,MCHT_FEE_COMMISSION_ID,MCHT_FEE_RETURN_ID)
);
CREATE TABLE MERCHANT_STATUSES (
	MCST_ID BIGINT IDENTITY NOT NULL,
	MCST_NAME VARCHAR(32) NOT NULL,
	MCST_DESCRIPTION VARCHAR(65535),
	MCST_ACTIVE INTEGER NOT NULL,
	MCST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (MCST_ID)
);
CREATE TABLE ORDERS (
	ORDR_ID BIGINT IDENTITY NOT NULL,
	ORDR_MERCHANT_NUMBER VARCHAR(32) NOT NULL,
	ORDR_AMOUNT FLOAT NOT NULL,
	ORDR_GOODS_NAME VARCHAR(128) NOT NULL,
	ORDR_GOODS_AMOUNT VARCHAR(128) NOT NULL,
	ORDR_CREATED_TIME TIMESTAMP NOT NULL,
	ORDR_UPDATED_TIME TIMESTAMP,
	ORDR_REMARK VARCHAR(65535),
	ORDR_ACTIVE INTEGER NOT NULL,
	ORDR_SITE_ID BIGINT NOT NULL,
	ORDR_ORST_ID BIGINT NOT NULL,
	ORDR_CRCY_ID BIGINT NOT NULL,
	ORDR_CSTM_ID BIGINT NOT NULL,
	PRIMARY KEY (ORDR_ID,ORDR_SITE_ID,ORDR_ORST_ID,ORDR_CRCY_ID,ORDR_CSTM_ID)
);
CREATE TABLE ORDER_STATUSES (
	ORST_ID BIGINT IDENTITY NOT NULL,
	ORST_NAME VARCHAR(32) NOT NULL,
	ORST_DESCRIPTION VARCHAR(65535),
	ORST_ACTIVE INTEGER NOT NULL,
	ORST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (ORST_ID)
);
CREATE TABLE PAYMENTS (
	PYMT_ID BIGINT IDENTITY NOT NULL,
	PYMT_AMOUNT FLOAT NOT NULL,
	PYMT_CREATED_TIME TIMESTAMP NOT NULL,
	PYMT_UPDATED_TIME TIMESTAMP,
	PYMT_SUCCESS_TIME TIMESTAMP,
	PYMT_BANK_TRANSACTION_NUMBER VARCHAR(128) NOT NULL,
	PYMT_BANK_NAME VARCHAR(128),
	PYMT_BANK_RETURN_CODE VARCHAR(128) NOT NULL,
	PYMT_BANK_ACCOUNT_NUMBER VARCHAR(128) NOT NULL,
	PYMT_BANK_ACCOUNT_EXP_DATE DATE NOT NULL,
	PYMT_REMARK VARCHAR(65535),
	PYMT_BILL_FIRST_NAME VARCHAR(32) NOT NULL,
	PYMT_BILL_LAST_NAME VARCHAR(32),
	PYMT_BILL_ADDRESS_1 VARCHAR(128) NOT NULL,
	PYMT_BILL_ADDRESS_2 VARCHAR(128),
	PYMT_BILL_CITY VARCHAR(32) NOT NULL,
	PYMT_BILL_STATE VARCHAR(32) NOT NULL,
	PYMT_BILL_ZIP_CODE VARCHAR(32) NOT NULL,
	PYMT_BILL_COUNTRY VARCHAR(32),
	PYMT_ACTIVE INTEGER NOT NULL,
	PYMT_PYST_ID BIGINT NOT NULL,
	PYMT_PYTP_ID BIGINT NOT NULL,
	PYMT_ORDR_ID BIGINT NOT NULL,
	PYMT_CRCY_ID BIGINT NOT NULL,
	PRIMARY KEY (PYMT_ID,PYMT_PYST_ID,PYMT_PYTP_ID,PYMT_ORDR_ID,PYMT_CRCY_ID)
);
CREATE TABLE PAYMENT_STATUSES (
	PYST_ID BIGINT IDENTITY NOT NULL,
	PYST_NAME VARCHAR(32) NOT NULL,
	PYST_DESCRIPTION VARCHAR(65535),
	PYST_ACTIVE INTEGER NOT NULL,
	PYST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (PYST_ID)
);
CREATE TABLE PAYMENT_TYPES (
	PYTP_ID BIGINT IDENTITY NOT NULL,
	PYTP_NAME VARCHAR(32) NOT NULL,
	PYTP_DESCRIPTION VARCHAR(65535),
	PYTP_ACTIVE INTEGER NOT NULL,
	PYTP_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (PYTP_ID)
);
CREATE TABLE PERMISSIONS (
	PRMS_ID BIGINT IDENTITY NOT NULL,
	PRMS_NAME VARCHAR(64) NOT NULL,
	PRMS_DESCRIPTION VARCHAR(65535),
	PRMS_ACTIVE INTEGER NOT NULL,
	PRMS_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (PRMS_ID)
);
CREATE TABLE REFUNDS (
	RFND_ID BIGINT IDENTITY NOT NULL,
	RFND_AMOUNT FLOAT NOT NULL,
	RFND_CREATED_TIME TIMESTAMP NOT NULL,
	RFND_UPDATED_TIME TIMESTAMP,
	RFND_SUCCESS_TIME TIMESTAMP,
	RFND_BANK_TRANSACTION_NUMBER VARCHAR(128) NOT NULL,
	RFND_BANK_NAME VARCHAR(128),
	RFND_BANK_RETURN_CODE VARCHAR(128) NOT NULL,
	RFND_BANK_ACCOUNT_NUMBER VARCHAR(128) NOT NULL,
	RFND_BANK_ACCOUNT_EXP_DATE DATE NOT NULL,
	RFND_REMARK VARCHAR(65535),
	RFND_BILL_FIRST_NAME VARCHAR(32) NOT NULL,
	RFND_BILL_LAST_NAME VARCHAR(32),
	RFND_BILL_ADDRESS_1 VARCHAR(128) NOT NULL,
	RFND_BILL_ADDRESS_2 VARCHAR(128),
	RFND_BILL_CITY VARCHAR(32) NOT NULL,
	RFND_BILL_STATE VARCHAR(32) NOT NULL,
	RFND_BILL_ZIP_CODE VARCHAR(32) NOT NULL,
	RFND_BILL_COUNTRY VARCHAR(32),
	RFND_ACTIVE INTEGER NOT NULL,
	RFND_RFST_ID BIGINT NOT NULL,
	RFND_ORDR_ID BIGINT NOT NULL,
	RFND_CRCY_ID BIGINT NOT NULL,
	PRIMARY KEY (RFND_ID,RFND_RFST_ID,RFND_ORDR_ID,RFND_CRCY_ID)
);
CREATE TABLE REFUND_STATUSES (
	RFST_ID BIGINT IDENTITY NOT NULL,
	RFST_NAME VARCHAR(32) NOT NULL,
	RFST_DESCRIPTION VARCHAR(65535),
	RFST_ACTIVE INTEGER NOT NULL,
	RFST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (RFST_ID)
);
CREATE TABLE "RETURNS" (
	RTRN_ID BIGINT IDENTITY NOT NULL,
	RTRN_MERCHANT_NUMBER VARCHAR(32) NOT NULL,
	RTRN_GOODS_NAME VARCHAR(128) NOT NULL,
	RTRN_GOODS_AMOUNT VARCHAR(128) NOT NULL,
	RTRN_CREATED_TIME TIMESTAMP NOT NULL,
	RTRN_UPDATED_TIME TIMESTAMP,
	RTRN_REMARK VARCHAR(65535),
	RTRN_ACTIVE INTEGER NOT NULL,
	RTRN_RTST_ID BIGINT NOT NULL,
	RTRN_ORDR_ID BIGINT NOT NULL,
	RTRN_AMOUNT FLOAT NOT NULL,
	PRIMARY KEY (RTRN_ID,RTRN_RTST_ID,RTRN_ORDR_ID)
);
CREATE TABLE RETURN_STATUSES (
	RTST_ID BIGINT IDENTITY NOT NULL,
	RTST_NAME VARCHAR(32) NOT NULL,
	RTST_DESCRIPTION VARCHAR(65535),
	RTST_ACTIVE INTEGER NOT NULL,
	RTST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (RTST_ID)
);
CREATE TABLE ROLES (
	ROLE_ID BIGINT IDENTITY NOT NULL,
	ROLE_NAME VARCHAR(64) NOT NULL,
	ROLE_DESCRIPTION VARCHAR(65535),
	ROLE_ACTIVE INTEGER NOT NULL,
	ROLE_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (ROLE_ID)
);
CREATE TABLE ROLE_PERMISSION_MAPPINGS (
	RPMP_ROLE_ID BIGINT NOT NULL,
	RPMP_PRMS_ID BIGINT NOT NULL,
	PRIMARY KEY (RPMP_ROLE_ID,RPMP_PRMS_ID)
);
CREATE TABLE SHIPMENTS (
	SHMT_ID BIGINT IDENTITY NOT NULL,
	SHMT_CARRIER VARCHAR(32) NOT NULL,
	SHMT_TRACKING_NUMBER VARCHAR(64) NOT NULL,
	SHMT_CREATED_TIME TIMESTAMP NOT NULL,
	SHMT_UPDATED_TIME TIMESTAMP,
	SHMT_REMARK VARCHAR(65535),
	SHMT_FIRST_NAME VARCHAR(32) NOT NULL,
	SHMT_LAST_NAME VARCHAR(32) NOT NULL,
	SHMT_ADDRESS_1 VARCHAR(128) NOT NULL,
	SHMT_ADDRESS_2 VARCHAR(128),
	SHMT_CITY VARCHAR(32) NOT NULL,
	SHMT_STATE VARCHAR(32) NOT NULL,
	SHMT_COUNTRY VARCHAR(32) NOT NULL,
	SHMT_ZIP_CODE VARCHAR(16) NOT NULL,
	SHMT_ACTIVE INTEGER NOT NULL,
	SHMT_SHST_ID BIGINT NOT NULL,
	SHMT_ORDR_ID BIGINT NOT NULL,
	PRIMARY KEY (SHMT_ID,SHMT_SHST_ID,SHMT_ORDR_ID)
);
CREATE TABLE SHIPMENT_STATUSES (
	SHST_ID BIGINT IDENTITY NOT NULL,
	SHST_NAME VARCHAR(32) NOT NULL,
	SHST_DESCRIPTION VARCHAR(65535),
	SHST_ACTIVE INTEGER NOT NULL,
	SHST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (SHST_ID)
);
CREATE TABLE SITES (
	SITE_ID BIGINT IDENTITY NOT NULL,
	SITE_NAME VARCHAR(32) NOT NULL,
	SITE_URL VARCHAR(128) NOT NULL,
	SITE_LOGO_IMAGE LONGVARBINARY,
	SITE_REMARK VARCHAR(65535),
	SITE_CREATED_TIME TIMESTAMP NOT NULL,
	SITE_UPDATED_TIME TIMESTAMP,
	SITE_ACTIVE INTEGER NOT NULL,
	SITE_SIST_ID BIGINT NOT NULL,
	SITE_MCHT_ID BIGINT NOT NULL,
	PRIMARY KEY (SITE_ID,SITE_SIST_ID,SITE_MCHT_ID)
);
CREATE TABLE SITE_STATUSES (
	SIST_ID BIGINT IDENTITY NOT NULL,
	SIST_NAME VARCHAR(32) NOT NULL,
	SIST_DESCRIPTION VARCHAR(65535),
	SIST_ACTIVE INTEGER NOT NULL,
	SIST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (SIST_ID)
);
CREATE TABLE USERS (
	USER_ID BIGINT IDENTITY NOT NULL,
	USER_USERNAME VARCHAR(32) NOT NULL,
	USER_PASSWORD VARCHAR(32) NOT NULL,
	USER_FIRST_NAME VARCHAR(32) NOT NULL,
	USER_LAST_NAME VARCHAR(32) NOT NULL,
	USER_EMAIL VARCHAR(32) NOT NULL,
	USER_PROFILE_IMAGE LONGVARBINARY,
	USER_REMARK VARCHAR(65535),
	USER_CREATED_TIME TIMESTAMP NOT NULL,
	USER_UPDATED_TIME TIMESTAMP,
	USER_ACTIVE INTEGER NOT NULL,
	USER_MCHT_ID BIGINT NOT NULL,
	USER_USST_ID BIGINT NOT NULL,
	PRIMARY KEY (USER_ID,USER_MCHT_ID,USER_USST_ID)
);
CREATE TABLE USER_ROLE_MAPPINGS (
	URMP_USER_ID BIGINT NOT NULL,
	URMP_ROLE_ID BIGINT NOT NULL,
	PRIMARY KEY (URMP_USER_ID,URMP_ROLE_ID)
);
CREATE TABLE USER_STATUSES (
	USST_ID BIGINT IDENTITY NOT NULL,
	USST_NAME VARCHAR(32) NOT NULL,
	USST_DESCRIPTION VARCHAR(65535),
	USST_ACTIVE INTEGER NOT NULL,
	USST_CODE VARCHAR(8) NOT NULL,
	PRIMARY KEY (USST_ID)
);
ALTER TABLE ACCOUNTS
	ADD FOREIGN KEY (ACNT_ACST_ID) 
	REFERENCES ACCOUNT_STATUSES (ACST_ID);

ALTER TABLE ACCOUNTS
	ADD FOREIGN KEY (ACNT_MCHT_ID) 
	REFERENCES MERCHANTS (MCHT_ID);

ALTER TABLE ACCOUNTS
	ADD FOREIGN KEY (ACNT_ACTP_ID) 
	REFERENCES ACCOUNT_TYPES (ACTP_ID);


ALTER TABLE ADMINISTRATORS
	ADD FOREIGN KEY (ADMN_ROLE_ID) 
	REFERENCES ROLES (ROLE_ID);


ALTER TABLE CREDENTIALS
	ADD FOREIGN KEY (CRDT_CRTP_ID) 
	REFERENCES CREDENTIAL_TYPES (CRTP_ID);

ALTER TABLE CREDENTIALS
	ADD FOREIGN KEY (CRDT_CRST_ID) 
	REFERENCES CREDENTIAL_STATUSES (CRST_ID);


ALTER TABLE CUSTOMERS
	ADD FOREIGN KEY (CSTM_CSST_ID) 
	REFERENCES CUSTOMER_STATUSES (CSST_ID);

ALTER TABLE CUSTOMERS
	ADD FOREIGN KEY (CSTM_CSLG_ID) 
	REFERENCES CUSTOMER_LOGINS (CSLG_ID);


ALTER TABLE CUSTOMER_LOGINS
	ADD FOREIGN KEY (CSLG_CSLS_ID) 
	REFERENCES CUSTOMER_LOGIN_STATUSES (CSLS_ID);


ALTER TABLE ENCRYPTIONS
	ADD FOREIGN KEY (ENCR_ENTP_ID) 
	REFERENCES ENCRYPTION_TYPES (ENTP_ID);


ALTER TABLE FEES
	ADD FOREIGN KEY (FEE_FETP_ID) 
	REFERENCES FEE_TYPES (FETP_ID);


ALTER TABLE MERCHANTS
	ADD FOREIGN KEY (MCHT_MCST_ID) 
	REFERENCES MERCHANT_STATUSES (MCST_ID);

ALTER TABLE MERCHANTS
	ADD FOREIGN KEY (MCHT_FEE_RETURN_ID) 
	REFERENCES FEES (FEE_ID);

ALTER TABLE MERCHANTS
	ADD FOREIGN KEY (MCHT_FEE_COMMISSION_ID) 
	REFERENCES FEES (FEE_ID);

ALTER TABLE MERCHANTS
	ADD FOREIGN KEY (MCHT_ENCR_ID) 
	REFERENCES ENCRYPTIONS (ENCR_ID);

ALTER TABLE MERCHANTS
	ADD FOREIGN KEY (MCHT_CRDT_ID) 
	REFERENCES CREDENTIALS (CRDT_ID);


ALTER TABLE ORDERS
	ADD FOREIGN KEY (ORDR_SITE_ID) 
	REFERENCES SITES (SITE_ID);

ALTER TABLE ORDERS
	ADD FOREIGN KEY (ORDR_ORST_ID) 
	REFERENCES ORDER_STATUSES (ORST_ID);

ALTER TABLE ORDERS
	ADD FOREIGN KEY (ORDR_CSTM_ID) 
	REFERENCES CUSTOMERS (CSTM_ID);

ALTER TABLE ORDERS
	ADD FOREIGN KEY (ORDR_CRCY_ID) 
	REFERENCES CURRENCIES (CRCY_ID);


ALTER TABLE PAYMENTS
	ADD FOREIGN KEY (PYMT_PYTP_ID) 
	REFERENCES PAYMENT_TYPES (PYTP_ID);

ALTER TABLE PAYMENTS
	ADD FOREIGN KEY (PYMT_PYST_ID) 
	REFERENCES PAYMENT_STATUSES (PYST_ID);

ALTER TABLE PAYMENTS
	ADD FOREIGN KEY (PYMT_ORDR_ID) 
	REFERENCES ORDERS (ORDR_ID);

ALTER TABLE PAYMENTS
	ADD FOREIGN KEY (PYMT_CRCY_ID) 
	REFERENCES CURRENCIES (CRCY_ID);


ALTER TABLE REFUNDS
	ADD FOREIGN KEY (RFND_CRCY_ID) 
	REFERENCES CURRENCIES (CRCY_ID);

ALTER TABLE REFUNDS
	ADD FOREIGN KEY (RFND_RFST_ID) 
	REFERENCES REFUND_STATUSES (RFST_ID);

ALTER TABLE REFUNDS
	ADD FOREIGN KEY (RFND_ORDR_ID) 
	REFERENCES ORDERS (ORDR_ID);


ALTER TABLE RETURNS
	ADD FOREIGN KEY (RTRN_RTST_ID) 
	REFERENCES RETURN_STATUSES (RTST_ID);

ALTER TABLE RETURNS
	ADD FOREIGN KEY (RTRN_ORDR_ID) 
	REFERENCES ORDERS (ORDR_ID);


ALTER TABLE ROLE_PERMISSION_MAPPINGS
	ADD FOREIGN KEY (RPMP_ROLE_ID) 
	REFERENCES ROLES (ROLE_ID);

ALTER TABLE ROLE_PERMISSION_MAPPINGS
	ADD FOREIGN KEY (RPMP_PRMS_ID) 
	REFERENCES PERMISSIONS (PRMS_ID);


ALTER TABLE SHIPMENTS
	ADD FOREIGN KEY (SHMT_SHST_ID) 
	REFERENCES SHIPMENT_STATUSES (SHST_ID);

ALTER TABLE SHIPMENTS
	ADD FOREIGN KEY (SHMT_ORDR_ID) 
	REFERENCES ORDERS (ORDR_ID);


ALTER TABLE SITES
	ADD FOREIGN KEY (SITE_MCHT_ID) 
	REFERENCES MERCHANTS (MCHT_ID);

ALTER TABLE SITES
	ADD FOREIGN KEY (SITE_SIST_ID) 
	REFERENCES SITE_STATUSES (SIST_ID);


ALTER TABLE USERS
	ADD FOREIGN KEY (USER_USST_ID) 
	REFERENCES USER_STATUSES (USST_ID);

ALTER TABLE USERS
	ADD FOREIGN KEY (USER_MCHT_ID) 
	REFERENCES MERCHANTS (MCHT_ID);


ALTER TABLE USER_ROLE_MAPPINGS
	ADD FOREIGN KEY (URMP_USER_ID) 
	REFERENCES USERS (USER_ID);

ALTER TABLE USER_ROLE_MAPPINGS
	ADD FOREIGN KEY (URMP_ROLE_ID) 
	REFERENCES ROLES (ROLE_ID);


INSERT INTO ACCOUNT_STATUSES(ACST_ID, ACST_NAME, ACST_DESCRIPTION, ACST_ACTIVE, ACST_CODE) VALUES (1, 'Normal', 'The merchant account is normal.', 1, '200');
INSERT INTO ACCOUNT_STATUSES(ACST_ID, ACST_NAME, ACST_DESCRIPTION, ACST_ACTIVE, ACST_CODE) VALUES (2, 'Frozen', 'The merchant account is frozen.', 1, '400');
INSERT INTO ACCOUNT_TYPES(ACTP_ID, ACTP_NAME, ACTP_DESCRIPTION, ACTP_ACTIVE, ACTP_CODE) VALUES (1, 'Bank', 'The account is the bank account number.', 1, '100');
INSERT INTO ACCOUNT_TYPES(ACTP_ID, ACTP_NAME, ACTP_DESCRIPTION, ACTP_ACTIVE, ACTP_CODE) VALUES (2, 'Card', 'The account is a bank card.', 1, '200');
INSERT INTO ADMINISTRATORS(ADMN_ID, ADMN_USERNAME, ADMN_PASSWORD, ADMN_FIRST_NAME, ADMN_LAST_NAME, ADMN_EMAIL, ADMN_PROFILE_IMAGE, ADMN_REMARK, ADMN_CREATED_TIME, ADMN_UPDATED_TIME, ADMN_ACTIVE, ADMN_ROLE_ID) VALUES (1, 'admin', 'admin', 'Admin', 'Admin', 'ironaire@gmail.com', null, null, '2015-02-28 17:08:25', null, 1, 1);
INSERT INTO CREDENTIAL_STATUSES(CRST_ID, CRST_NAME, CRST_DESCRIPTION, CRST_ACTIVE, CRST_CODE) VALUES (1, 'Submitted', 'The credential is submitted for approval.', 1, '400');
INSERT INTO CREDENTIAL_STATUSES(CRST_ID, CRST_NAME, CRST_DESCRIPTION, CRST_ACTIVE, CRST_CODE) VALUES (2, 'Approved', 'The credential is approved.', 1, '500');
INSERT INTO CREDENTIAL_STATUSES(CRST_ID, CRST_NAME, CRST_DESCRIPTION, CRST_ACTIVE, CRST_CODE) VALUES (3, 'Denied', 'The credential is denied.', 1, '502');
INSERT INTO CREDENTIAL_STATUSES(CRST_ID, CRST_NAME, CRST_DESCRIPTION, CRST_ACTIVE, CRST_CODE) VALUES (4, 'Expired', 'The credential has expired.', 1, '404');
INSERT INTO CREDENTIAL_TYPES(CRTP_ID, CRTP_NAME, CRTP_DESCRIPTION, CRTP_ACTIVE, CRTP_CODE) VALUES (1, 'Certificate', 'Certificate', 1, '100');
INSERT INTO CURRENCIES(CRCY_ID, CRCY_NAME, CRCY_DESCRIPTION, CRCY_ACTIVE, CRCY_CODE) VALUES (1, 'USD', 'US Dollar', 1, '100');
INSERT INTO CURRENCIES(CRCY_ID, CRCY_NAME, CRCY_DESCRIPTION, CRCY_ACTIVE, CRCY_CODE) VALUES (2, 'RMB', 'Chinese Yuan', 1, '101');
INSERT INTO CUSTOMER_LOGIN_STATUSES(CSLS_ID, CSLS_NAME, CSLS_DESCRIPTION, CSLS_ACTIVE, CSLS_CODE) VALUES (1, 'Frozen', 'Frozen', 1, '500');
INSERT INTO CUSTOMER_LOGIN_STATUSES(CSLS_ID, CSLS_NAME, CSLS_DESCRIPTION, CSLS_ACTIVE, CSLS_CODE) VALUES (2, 'Normal', 'Normal', 1, '200');
INSERT INTO CUSTOMER_STATUSES(CSST_ID, CSST_NAME, CSST_DESCRIPTION, CSST_ACTIVE, CSST_CODE) VALUES (1, 'Normal', 'Normal', 1, '200');
INSERT INTO CUSTOMER_STATUSES(CSST_ID, CSST_NAME, CSST_DESCRIPTION, CSST_ACTIVE, CSST_CODE) VALUES (2, 'Frozen', 'Frozen', 1, '500');
INSERT INTO ENCRYPTION_TYPES(ENTP_ID, ENTP_NAME, ENTP_DESCRIPTION, ENTP_ACTIVE, ENTP_CODE) VALUES (1, 'MD5', 'MD5 Algorithm', 1, '100');
INSERT INTO ENCRYPTION_TYPES(ENTP_ID, ENTP_NAME, ENTP_DESCRIPTION, ENTP_ACTIVE, ENTP_CODE) VALUES (2, 'SHA', 'SHA Algorithm', 1, '101');
INSERT INTO FEE_TYPES(FETP_ID, FETP_NAME, FETP_DESCRIPTION, FETP_ACTIVE, FETP_CODE) VALUES (1, 'Static', 'Static amount for every transaction', 1, '100');
INSERT INTO FEE_TYPES(FETP_ID, FETP_NAME, FETP_DESCRIPTION, FETP_ACTIVE, FETP_CODE) VALUES (2, 'Percentage', 'Percentage based on the transaction amount', 1, '101');
INSERT INTO MERCHANT_STATUSES(MCST_ID, MCST_NAME, MCST_DESCRIPTION, MCST_ACTIVE, MCST_CODE) VALUES (1, 'Normal', 'Normal', 1, '200');
INSERT INTO MERCHANT_STATUSES(MCST_ID, MCST_NAME, MCST_DESCRIPTION, MCST_ACTIVE, MCST_CODE) VALUES (2, 'Frozen', 'Frozen', 1, '500');
INSERT INTO ORDER_STATUSES(ORST_ID, ORST_NAME, ORST_DESCRIPTION, ORST_ACTIVE, ORST_CODE) VALUES (1, 'Initiated', 'The order is initiated.', 1, '400');
INSERT INTO ORDER_STATUSES(ORST_ID, ORST_NAME, ORST_DESCRIPTION, ORST_ACTIVE, ORST_CODE) VALUES (2, 'Confirmed', 'The order is confirmed.', 1, '500');
INSERT INTO ORDER_STATUSES(ORST_ID, ORST_NAME, ORST_DESCRIPTION, ORST_ACTIVE, ORST_CODE) VALUES (3, 'Paid', 'The order is paid.', 1, '401');
INSERT INTO ORDER_STATUSES(ORST_ID, ORST_NAME, ORST_DESCRIPTION, ORST_ACTIVE, ORST_CODE) VALUES (4, 'Preparing for Shipment', 'The order is parpared for shipment, cannot be cancel at this stage.', 1, '501');
INSERT INTO ORDER_STATUSES(ORST_ID, ORST_NAME, ORST_DESCRIPTION, ORST_ACTIVE, ORST_CODE) VALUES (5, 'Cancelled', 'The order is cancelled.', 1, '402');
INSERT INTO ORDER_STATUSES(ORST_ID, ORST_NAME, ORST_DESCRIPTION, ORST_ACTIVE, ORST_CODE) VALUES (6, 'Shipped', 'The order is shipped.', 1, '502');
INSERT INTO ORDER_STATUSES(ORST_ID, ORST_NAME, ORST_DESCRIPTION, ORST_ACTIVE, ORST_CODE) VALUES (7, 'Delivered', 'The order is delivered.', 1, '503');
INSERT INTO ORDER_STATUSES(ORST_ID, ORST_NAME, ORST_DESCRIPTION, ORST_ACTIVE, ORST_CODE) VALUES (8, 'Returned', 'The order is returned.', 1, '403');
INSERT INTO ORDER_STATUSES(ORST_ID, ORST_NAME, ORST_DESCRIPTION, ORST_ACTIVE, ORST_CODE) VALUES (9, 'Refunded', 'The order is refunded.', 1, '504');
INSERT INTO PAYMENT_STATUSES(PYST_ID, PYST_NAME, PYST_DESCRIPTION, PYST_ACTIVE, PYST_CODE) VALUES (1, 'Approved', 'Approved', 1, '500');
INSERT INTO PAYMENT_STATUSES(PYST_ID, PYST_NAME, PYST_DESCRIPTION, PYST_ACTIVE, PYST_CODE) VALUES (2, 'Declined', 'Declined', 1, '501');
INSERT INTO PAYMENT_TYPES(PYTP_ID, PYTP_NAME, PYTP_DESCRIPTION, PYTP_ACTIVE, PYTP_CODE) VALUES (1, 'Credit Card', 'Credit Card', 1, '100');
INSERT INTO PAYMENT_TYPES(PYTP_ID, PYTP_NAME, PYTP_DESCRIPTION, PYTP_ACTIVE, PYTP_CODE) VALUES (2, 'Debit Card', 'Debit Card', 1, '101');
INSERT INTO REFUND_STATUSES(RFST_ID, RFST_NAME, RFST_DESCRIPTION, RFST_ACTIVE, RFST_CODE) VALUES (1, 'Issued', 'Issued', 1, '500');
INSERT INTO REFUND_STATUSES(RFST_ID, RFST_NAME, RFST_DESCRIPTION, RFST_ACTIVE, RFST_CODE) VALUES (2, 'Funded', 'Funded', 1, '501');
INSERT INTO RETURN_STATUSES(RTST_ID, RTST_NAME, RTST_DESCRIPTION, RTST_ACTIVE, RTST_CODE) VALUES (1, 'Shipped', 'Shipped', 1, '400');
INSERT INTO RETURN_STATUSES(RTST_ID, RTST_NAME, RTST_DESCRIPTION, RTST_ACTIVE, RTST_CODE) VALUES (2, 'Delivered', 'Delivered', 1, '401');
INSERT INTO ROLES(ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION, ROLE_ACTIVE, ROLE_CODE) VALUES (1, 'ROLE_ADMIN', 'System Admin', 1, '100');
INSERT INTO ROLES(ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION, ROLE_ACTIVE, ROLE_CODE) VALUES (2, 'ROLE_MERCHANT_ADMIN', 'Merchant Admin', 1, '200');
INSERT INTO ROLES(ROLE_ID, ROLE_NAME, ROLE_DESCRIPTION, ROLE_ACTIVE, ROLE_CODE) VALUES (3, 'ROLE_MERCHANT_OPERATOR', 'Merchant Operator', 1, '201');
INSERT INTO SHIPMENT_STATUSES(SHST_ID, SHST_NAME, SHST_DESCRIPTION, SHST_ACTIVE, SHST_CODE) VALUES (1, 'Shipped', 'Shipped', 1, '500');
INSERT INTO SHIPMENT_STATUSES(SHST_ID, SHST_NAME, SHST_DESCRIPTION, SHST_ACTIVE, SHST_CODE) VALUES (2, 'Delivered', 'Delivered', 1, '501');
INSERT INTO SHIPMENT_STATUSES(SHST_ID, SHST_NAME, SHST_DESCRIPTION, SHST_ACTIVE, SHST_CODE) VALUES (3, 'Lost', 'Lost', 1, '400');
INSERT INTO SHIPMENT_STATUSES(SHST_ID, SHST_NAME, SHST_DESCRIPTION, SHST_ACTIVE, SHST_CODE) VALUES (4, 'Damaged', 'Damaged', 1, '401');
INSERT INTO SITE_STATUSES(SIST_ID, SIST_NAME, SIST_DESCRIPTION, SIST_ACTIVE, SIST_CODE) VALUES (1, 'Created', 'Created and wait for approval', 1, '400');
INSERT INTO SITE_STATUSES(SIST_ID, SIST_NAME, SIST_DESCRIPTION, SIST_ACTIVE, SIST_CODE) VALUES (2, 'Approved', 'Approved to operation', 1, '500');
INSERT INTO SITE_STATUSES(SIST_ID, SIST_NAME, SIST_DESCRIPTION, SIST_ACTIVE, SIST_CODE) VALUES (3, 'Frozen', 'Frozen', 1, '401');
INSERT INTO SITE_STATUSES(SIST_ID, SIST_NAME, SIST_DESCRIPTION, SIST_ACTIVE, SIST_CODE) VALUES (4, 'Declined', 'Declined', 1, '501');
INSERT INTO USER_STATUSES(USST_ID, USST_NAME, USST_DESCRIPTION, USST_ACTIVE, USST_CODE) VALUES (1, 'Normal', 'Normal', 1, '100');
INSERT INTO USER_STATUSES(USST_ID, USST_NAME, USST_DESCRIPTION, USST_ACTIVE, USST_CODE) VALUES (2, 'Deactived', 'Deactived', 1, '400');
INSERT INTO USER_STATUSES(USST_ID, USST_NAME, USST_DESCRIPTION, USST_ACTIVE, USST_CODE) VALUES (3, 'Frozen', 'Frozen', 1, '501');
